### ISSUE TITLE
len(character_row) error

### ISSUE THREAD

**Issue by DrLarck** [DrLarck/dragonbotz#57]
Traceback : 

```
connection was closed in the middle of operation
Ignoring exception in on_message                                                                                     
Traceback (most recent call last):                                                                                     
File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 333, in _run_event                               
await coro(*args, **kwargs)                                                                                        
File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 943, in on_message                     
await self.process_commands(message)                                                                               
File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 940, in process_commands               
await self.invoke(ctx)                                                                                             
File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke                         
await ctx.command.invoke(ctx)                                                                                      
File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1329, in invoke                       
await ctx.invoked_subcommand.invoke(ctx)                                                                           
File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 851, in invoke                        
await self.prepare(ctx)                                                                                            
File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 778, in prepare                       
if not await self.can_run(ctx):                                                                                    
File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1076, in can_run                      
return await discord.utils.async_all(predicate(ctx) for predicate in predicates)                                   
File "/usr/local/lib/python3.8/site-packages/discord/utils.py", line 340, in async_all                                 
elem = await elem                                                                                                  
File "/home/app/bot/dragonbotz/discordballz-origins/utility/command/checker.py", line 160, in has_team                 
team = await player.combat.get_team()                                                                              
File "/home/app/bot/dragonbotz/discordballz-origins/utility/entity/player.py", line 867, in get_team                   
character = await char_getter.get_from_unique(self.player.client, self.__database, unique_id)                      
File "/home/app/bot/dragonbotz/discordballz-origins/utility/entity/character.py", line 623, in get_from_unique        
if len(character_row) > 0:
```

**Comment by DrLarck** [comment]
uncomplete traceback
